# =================================================================
# Licensed Materials - Property of IBM
#
# (c) Copyright IBM Corp. 2014 All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
# =================================================================
guard 'rack', port: 9292 do
  watch('Guardfile')
  watch('config.ru')
  watch('Gemfile.lock')
  watch(%r{^lib/.*})
end
