# Example usage ansible-playbook deploy-metrics.yaml -i hosts.yaml
- name: start metrics forwarder
  hosts: vm
  tasks:
    - name: Install docker-py as a workaround for Ansible issue
      sudo: yes
      pip: name=docker-py


    - name: metrics crawler forwarder
      docker:
        name: statsd
        image: "{{statsd_registry}}/alchemy/containers-statsd-forwarder"
        docker_api_version: 1.21
        registry: "{{statsd_registry}}"
        insecure_registry: yes
        command: "
          -hostname {{ansible_hostname}}
          -graphite-host {{ graphite_host }}
          -graphite-port 9095
          -graphite-prefix {{logmet_tenant_id}}.{{ ansible_hostname }}.
          -graphite-tenant-id {{ logmet_tenant_id }}
          -graphite-logging-password {{ logmet_tenant_password }}"
        hostname: "{{ ansible_hostname }}"
        state: reloaded
        pull: missing
        volumes:
          - /var/log/containers/collectd:/var/log/containers/collectd
          - /var/run/docker.sock:/var/run/docker.sock
