### This works for my vm, you'll need to put in the hostname for your own.
# logmet_tenant_id & logmet_tenant_password should be the same
[vm]
francis

[vm:vars]
statsd_registry=alchemyregistry.hursley.ibm.com:5000
graphite_host=metrics.stage1.opvis.bluemix.net
logmet_tenant_id=a63d60f6-d9ce-402a-9d06-b9263acc15d4
logmet_tenant_password=n_rcmJvEpexR
ansible_host=francis.hursley.ibm.com
remote_user=root
ansible_user=root

### EXAMPLE DEV, NEEDS WORK
[dev]
dev-mon01-annotator-1
dev-mon01-advisor-1
dev-mon01-kafka-1

[dev:vars]
statsd_registry=dev-mon01-infra-deploy-01.alchemy.ibm.com:5000
graphite_host=metrics.stage1.opvis.bluemix.net
logmet_tenant_id={{dev_tenant_id}}
logmet_tenant_password={{dev_logmet_password}}
ansible_host=dev-mon01
remote_user=root
ansible_user=root

### EXAMPLE STAGE, NEEDS WORK
[stage]
stage-lon01-annotator-1
stage-lon01-advisor-1
stage-lon01-kafka-1

[stage:vars]
statsd_registry=stage-lon01-infra-deploy-01.alchemy.ibm.com:5000
graphite_host=metrics.stage1.opvis.bluemix.net
logmet_tenant_id={{stage_tenant_id}}
logmet_tenant_password={{stage_logmet_password}}
ansible_host=stage-lon01
remote_user=root
ansible_user=root

### EXAMPLE PROD, NEEDS WORK
[prod]
prod-lon01-annotator-1
prod-lon01-advisor-1
prod-lon01-kafka-1

[prod:vars]
statsd_registry=prod-dal09-infra-deploy-01.alchemy.ibm.com:5000
graphite_host=metrics.ng.opvis.bluemix.net
logmet_tenant_id={{prod_tenant_id}}
logmet_tenant_password={{prod_logmet_password}}
ansible_host=stage-dal09
remote_user=root
ansible_user=root