#!/bin/bash

BASE_IMG="cloudsight/kelk-base"

ES_IMG="cloudsight/elasticsearch"
KAFKA_IMG="cloudsight/kafka"
INDEXER_IMG="cloudsight/indexer"
GENERIC_INDEXER_IMG="cloudsight/generic-indexer"
NOTIFICATION_INDEXER_IMG="cloudsight/notification-indexer"
SEARCH_IMG="cloudsight/searchservice"
CONFIG_PARSER_IMG="cloudsight/config-parser-kelk"
VULNERABILITY_ANNOTATOR_IMG="cloudsight/vulnerability_annotator"
NOTIFICATION_PROCESSOR_IMG="cloudsight/notification_processor"
COMPLIANCE_ANNOTATOR_IMG="cloudsight/compliance_annotator"
USN_CRAWLER_IMG="cloudsight/usncrawler"
REGISTRY_UPDATE_IMG="cloudsight/registry-update"
REGISTRY_MONITOR_IMG="cloudsight/registry-monitor"
PASSWORD_ANNOTATOR_IMG="cloudsight/password-annotator"
VASTAT_REPORTER_IMG="cloudsight/vastat-reporter"
TIMEMACHINE_IMG="cloudsight/timemachine"

ES_CONT="cloudsight-elasticsearch"
KAFKA_CONT="cloudsight-kafka"
INDEXER_CONT="cloudsight-indexer"
LOG_INDEXER_CONT="cloudsight-logindexer"
SEARCH_CONT="cloudsight-searchservice"
CONFIG_PARSER_CONT="cloudsight-config-parser"
COMPLIANCE_INDEXER_CONT="cloudsight-compliance-indexer"
COMPLIANCE_ANNOTATOR_CONT="cloudsight-compliance-annotator"
VULNERABILITY_INDEXER_CONT="cloudsight-vulnerability-indexer"
VULNERABILITY_ANNOTATOR_CONT="cloudsight-vulnerability-annotator"
NOTIFICATION_PROCESSOR_CONT="cloudsight-notification-processor"
NOTIFICATION_INDEXER_CONT="cloudsight-notification-indexer"
USNCRAWLER_CONT="cloudsight-usncrawler"
REGISTRY_UPDATE_CONT="cloudsight-registry-update"
REGISTRY_MONITOR_CONT="cloudsight-registry-monitor"
PASSWORD_ANNOTATOR_CONT="cloudsight-password-annotator"
VASTAT_REPORTER_CONT="cloudsight-vastat-reporter"
TIMEMACHINE_CONT="cloudsight-timemachine"

CONTAINERS=($ES_CONT $KAFKA_CONT \
        $INDEXER_CONT $LOG_INDEXER_CONT \
        $SEARCH_CONT $CONFIG_PARSER_CONT \
        $COMPLIANCE_INXEDER_CONT \
        $VULNERABILITY_INDEXER_CONT \
        $VULNERABILITY_ANNOTATOR_CONT \
        $REGISTRY_UPDATE_CONT \
        $REGISTRY_MONITOR_CONT \
        $NOTIFICATION_INDEXER_CONT \
        $NOTIFICATION_PROCESSOR_CONT\
        $PASSWORD_ANNOTATOR_CONT\
        $VASTAT_REPORTER_CONT\
        $TIMEMACHINE_CONT)

DEPLOYMENT_IMAGES=($ES_IMG $KAFKA_IMG \
        $INDEXER_IMG $GENERIC_INDEXER_IMG \
        $NOTIFICATION_INDEXER_IMG \
        $SEARCH_IMG $CONFIG_PARSER_IMG \
        $VULNERABILITY_ANNOTATOR_IMG \
        $NOTIFICATION_PROCESSOR_IMG \
        $COMPLIANCE_ANNOTATOR_IMG \
        $USN_CRAWLER_IMG $REGISTRY_UPDATE_IMG \
        $REGISTRY_MONITOR_IMG\
        $PASSWORD_ANNOTATOR_IMG\
        $VASTAT_REPORTER_IMG\
        $TIMEMACHINE_IMG)
