#!/bin/bash

BASE_IMG="cloudsight/kelk-base"

ES_IMG="cloudsight/elasticsearch"
KAFKA_IMG="cloudsight/kafka"
INDEXER_IMG="cloudsight/indexer"
GENERIC_INDEXER_IMG="cloudsight/generic-indexer"
NOTIFICATION_INDEXER_IMG="cloudsight/notification-indexer"
SEARCH_IMG="cloudsight/searchservice"
CONFIG_PARSER_IMG="cloudsight/config-parser-kelk"
VULNERABILITY_ANNOTATOR_IMG="cloudsight/vulnerability-annotator"
NOTIFICATION_PROCESSOR_IMG="cloudsight/notification-processor"
COMPLIANCE_ANNOTATOR_IMG="cloudsight/compliance-annotator"
USN_CRAWLER_IMG="cloudsight/usncrawler"
REGISTRY_UPDATE_IMG="cloudsight/registry-update"
REGISTRY_MONITOR_IMG="cloudsight/registry-monitor"
PASSWORD_ANNOTATOR_IMG="cloudsight/password-annotator"
VASTAT_REPORTER_IMG="cloudsight/vastat-reporter"
TIMEMACHINE_IMG="cloudsight/timemachine"
CONSUL_IMG="alchemy/containers-consul"
CONFIG_AND_METRICS_CRAWLER_IMG="cloudsight/config-and-metrics-crawler"
METRICS_SERVER_IMG="cloudsight/metrics-server"
MASTER_METRICS_SERVER_IMG="cloudsight/uptime-server"
IMAGE_RESCANNER_IMG="cloudsight/image-rescanner"
MT_LOGSTASH_FORWARDER_IMG="cloudsight/mt-logstash-forwarder"


ES_CONT="cloudsight-elasticsearch"
KAFKA_CONT="cloudsight-kafka"
INDEXER_CONT="cloudsight-indexer"
LOG_INDEXER_CONT="cloudsight-logindexer"
SEARCH_CONT="cloudsight-searchservice"
CONFIG_PARSER_CONT="cloudsight-config-parser"
COMPLIANCE_INDEXER_CONT="cloudsight-compliance-indexer"
COMPLIANCE_ANNOTATOR_CONT="cloudsight-compliance-annotator"
VULNERABILITY_INDEXER_CONT="cloudsight-vulnerability-indexer"
VULNERABILITY_ANNOTATOR_CONT="cloudsight-vulnerability-annotator"
NOTIFICATION_PROCESSOR_CONT="cloudsight-notification-processor"
NOTIFICATION_INDEXER_CONT="cloudsight-notification-indexer"
USNCRAWLER_CONT="cloudsight-usncrawler"
REGISTRY_UPDATE_CONT="cloudsight-registry-update"
REGISTRY_MONITOR_CONT="cloudsight-registry-monitor"
REGISTRY_MONITOR_SINGLERUN_CONT="cloudsight-registry-monitor-singlerun"
PASSWORD_ANNOTATOR_CONT="cloudsight-password-annotator"
VASTAT_REPORTER_CONT="cloudsight-vastat-reporter"
TIMEMACHINE_CONT="cloudsight-timemachine"
CONSUL_CONT="cloudsight-consul"
CONFIG_AND_METRICS_CRAWLER_CONT="cloudsight-config-and-metrics-crawler"
METRICS_SERVER_CONT="cloudsight-metrics-server"
MASTER_METRICS_SERVER_CONT="cloudsight-uptime-server"
IMAGE_RESCANNER_CONT="cloudsight-image-rescanner"
MT_LOGSTASH_FORWARDER_CONT="cloudsight-mt-logstash-forwarder"

CONTAINERS=($ES_CONT $KAFKA_CONT \
        $INDEXER_CONT $LOG_INDEXER_CONT \
        $SEARCH_CONT $CONFIG_PARSER_CONT \
        $COMPLIANCE_INXEDER_CONT \
        $VULNERABILITY_INDEXER_CONT \
        $VULNERABILITY_ANNOTATOR_CONT \
        $REGISTRY_UPDATE_CONT \
        $REGISTRY_MONITOR_CONT \
        $NOTIFICATION_INDEXER_CONT \
        $NOTIFICATION_PROCESSOR_CONT \
        $PASSWORD_ANNOTATOR_CONT \
        $VASTAT_REPORTER_CONT \
        $TIMEMACHINE_CONT \
        $IMAGE_RESCANNER_CONT \
        $CONFIG_AND_METRICS_CRAWLER_CONT \
        $METRICS_SERVER_CONT\
        $MASTER_METRICS_SERVER_CONT \
        $MT_LOGSTASH_FORWARDER_CONT)

DEPLOYMENT_IMAGES=($ES_IMG $KAFKA_IMG $CONSUL_IMG \
        $INDEXER_IMG $GENERIC_INDEXER_IMG \
        $NOTIFICATION_INDEXER_IMG \
        $SEARCH_IMG $CONFIG_PARSER_IMG \
        $VULNERABILITY_ANNOTATOR_IMG \
        $NOTIFICATION_PROCESSOR_IMG \
        $COMPLIANCE_ANNOTATOR_IMG \
        $USN_CRAWLER_IMG $REGISTRY_UPDATE_IMG \
        $REGISTRY_MONITOR_IMG \
        $PASSWORD_ANNOTATOR_IMG \
        $VASTAT_REPORTER_IMG \
        $TIMEMACHINE_IMG \
        $IMAGE_RESCANNER_IMG \
        $CONFIG_AND_METRICS_CRAWLER_IMG \
        $METRICS_SERVER_IMG \
        $MASTER_METRICS_SERVER_IMG \
        $MT_LOGSTASH_FORWARDER_IMG)

KELK_BASE_DEPENDENT_IMAGES=($ES_IMG $KAFKA_IMG \
        $INDEXER_IMG $GENERIC_INDEXER_IMG \
        $NOTIFICATION_INDEXER_IMG \
        $SEARCH_IMG $TIMEMACHINE_IMG)

