#!/usr/bin/env ruby
# =================================================================
# Licensed Materials - Property of IBM
#
# (c) Copyright IBM Corp. 2014 All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
# =================================================================
begin
  require_relative '../vendor/bundle/bundler/setup'
rescue LoadError
  require 'bundler'
  Bundler.setup
end

require 'openssl'
require 'net/http'
require 'uri'
require 'json'

PORT = '9292'

uri = URI.parse("https://localhost:#{PORT}/api/systems")

http = Net::HTTP.new(uri.host, uri.port)
http.use_ssl = true
http.verify_mode = OpenSSL::SSL::VERIFY_NONE
http.read_timeout = 600

request = Net::HTTP::Get.new(uri.request_uri)

response = http.request(request)
systems = JSON.parse(response.body)

exit(1) unless systems.is_a?(Array) && response.code == '200'

systems.each do |system|
  request = Net::HTTP::Get.new("/api/systems/#{system['id']}/run?use_period=true")
  http.request(request)
end

