#!/usr/bin/env ruby
# =================================================================
# Licensed Materials - Property of IBM
#
# (c) Copyright IBM Corp. 2014 All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
# =================================================================
begin
  require_relative '../vendor/bundle/bundler/setup'
rescue LoadError
  require 'bundler'
  Bundler.setup
end

require 'puma/cli'
Puma::CLI.new(ARGV).run
