[1;32mSSHD  listening       RUNNING  package.sshd.entrypoint.port-mapped.centos-6[0m
other not-listening   RUNNING  package.sshd.entrypoint.no-port-mapped.centos-6
other not-listening   RUNNING  package.sshd.entrypoint.other-port-mapped.centos-6
[1;32mSSHD  listening       RUNNING  package.sshd.cmd.port-mapped.centos-6[0m
other not-listening   RUNNING  package.sshd.cmd.no-port-mapped.centos-6
other not-listening   RUNNING  package.sshd.cmd.other-port-mapped.centos-6
[1;32mSSHD  listening       RUNNING  package.sshd-from-supervisord.entrypoint.port-mapped.centos-6[0m
other not-listening   RUNNING  package.sshd-from-supervisord.entrypoint.no-port-mapped.centos-6
other not-listening   RUNNING  package.sshd-from-supervisord.entrypoint.other-port-mapped.centos-6
[1;32mSSHD  listening       RUNNING  package.sshd-from-supervisord.cmd.port-mapped.centos-6[0m
other not-listening   RUNNING  package.sshd-from-supervisord.cmd.no-port-mapped.centos-6
other not-listening   RUNNING  package.sshd-from-supervisord.cmd.other-port-mapped.centos-6
[1;32mSSHD  listening       RUNNING  package.sshd-from-bash.entrypoint.port-mapped.centos-6[0m
other not-listening   RUNNING  package.sshd-from-bash.entrypoint.no-port-mapped.centos-6
other not-listening   RUNNING  package.sshd-from-bash.entrypoint.other-port-mapped.centos-6
[1;32mSSHD  listening       RUNNING  package.sshd-from-bash.cmd.port-mapped.centos-6[0m
other not-listening   RUNNING  package.sshd-from-bash.cmd.no-port-mapped.centos-6
other not-listening   RUNNING  package.sshd-from-bash.cmd.other-port-mapped.centos-6
other not-listening   RUNNING  package.sleep.entrypoint.port-mapped.centos-6
other not-listening   RUNNING  package.sleep.entrypoint.no-port-mapped.centos-6
other not-listening   RUNNING  package.sleep.entrypoint.other-port-mapped.centos-6
other not-listening   RUNNING  package.sleep.cmd.port-mapped.centos-6
other not-listening   RUNNING  package.sleep.cmd.no-port-mapped.centos-6
other not-listening   RUNNING  package.sleep.cmd.other-port-mapped.centos-6
other not-listening   RUNNING  package.sleep-from-supervisord.entrypoint.port-mapped.centos-6
other not-listening   RUNNING  package.sleep-from-supervisord.entrypoint.no-port-mapped.centos-6
other not-listening   RUNNING  package.sleep-from-supervisord.entrypoint.other-port-mapped.centos-6
other not-listening   RUNNING  package.sleep-from-supervisord.cmd.port-mapped.centos-6
other not-listening   RUNNING  package.sleep-from-supervisord.cmd.no-port-mapped.centos-6
other not-listening   RUNNING  package.sleep-from-supervisord.cmd.other-port-mapped.centos-6
other not-listening   RUNNING  package.sleep-from-bash.entrypoint.port-mapped.centos-6
other not-listening   RUNNING  package.sleep-from-bash.entrypoint.no-port-mapped.centos-6
other not-listening   RUNNING  package.sleep-from-bash.entrypoint.other-port-mapped.centos-6
other not-listening   RUNNING  package.sleep-from-bash.cmd.port-mapped.centos-6
other not-listening   RUNNING  package.sleep-from-bash.cmd.no-port-mapped.centos-6
other not-listening   RUNNING  package.sleep-from-bash.cmd.other-port-mapped.centos-6
other listening       RUNNING  package.nc-server.entrypoint.port-mapped.centos-6
other not-listening   RUNNING  package.nc-server.entrypoint.no-port-mapped.centos-6
other not-listening   RUNNING  package.nc-server.entrypoint.other-port-mapped.centos-6
other listening       RUNNING  package.nc-server.cmd.port-mapped.centos-6
other not-listening   RUNNING  package.nc-server.cmd.no-port-mapped.centos-6
other not-listening   RUNNING  package.nc-server.cmd.other-port-mapped.centos-6
other listening       RUNNING  package.nc-server-from-supervisord.entrypoint.port-mapped.centos-6
other not-listening   RUNNING  package.nc-server-from-supervisord.entrypoint.no-port-mapped.centos-6
other not-listening   RUNNING  package.nc-server-from-supervisord.entrypoint.other-port-mapped.centos-6
other listening       RUNNING  package.nc-server-from-supervisord.cmd.port-mapped.centos-6
other not-listening   RUNNING  package.nc-server-from-supervisord.cmd.no-port-mapped.centos-6
other not-listening   RUNNING  package.nc-server-from-supervisord.cmd.other-port-mapped.centos-6
other listening       RUNNING  package.nc-server-from-bash.entrypoint.port-mapped.centos-6
other not-listening   RUNNING  package.nc-server-from-bash.entrypoint.no-port-mapped.centos-6
other not-listening   RUNNING  package.nc-server-from-bash.entrypoint.other-port-mapped.centos-6
other listening       RUNNING  package.nc-server-from-bash.cmd.port-mapped.centos-6
other not-listening   RUNNING  package.nc-server-from-bash.cmd.no-port-mapped.centos-6
other not-listening   RUNNING  package.nc-server-from-bash.cmd.other-port-mapped.centos-6
[0;31mother not-listening   CRASHED  package.wrong-path-sshd.entrypoint.port-mapped.centos-6[0m
[0;31mother not-listening   CRASHED  package.wrong-path-sshd.entrypoint.no-port-mapped.centos-6[0m
[0;31mother not-listening   CRASHED  package.wrong-path-sshd.entrypoint.other-port-mapped.centos-6[0m
[0;31mother not-listening   CRASHED  package.wrong-path-sshd.cmd.port-mapped.centos-6[0m
[0;31mother not-listening   CRASHED  package.wrong-path-sshd.cmd.no-port-mapped.centos-6[0m
[0;31mother not-listening   CRASHED  package.wrong-path-sshd.cmd.other-port-mapped.centos-6[0m
other not-listening   RUNNING  package.wrong-path-sshd-from-supervisord.entrypoint.port-mapped.centos-6
other not-listening   RUNNING  package.wrong-path-sshd-from-supervisord.entrypoint.no-port-mapped.centos-6
other not-listening   RUNNING  package.wrong-path-sshd-from-supervisord.entrypoint.other-port-mapped.centos-6
other not-listening   RUNNING  package.wrong-path-sshd-from-supervisord.cmd.port-mapped.centos-6
other not-listening   RUNNING  package.wrong-path-sshd-from-supervisord.cmd.no-port-mapped.centos-6
other not-listening   RUNNING  package.wrong-path-sshd-from-supervisord.cmd.other-port-mapped.centos-6
[0;31mother not-listening   CRASHED  package.wrong-path-sshd-from-bash.entrypoint.port-mapped.centos-6[0m
[0;31mother not-listening   CRASHED  package.wrong-path-sshd-from-bash.entrypoint.no-port-mapped.centos-6[0m
[0;31mother not-listening   CRASHED  package.wrong-path-sshd-from-bash.entrypoint.other-port-mapped.centos-6[0m
[0;31mother not-listening   CRASHED  package.wrong-path-sshd-from-bash.cmd.port-mapped.centos-6[0m
[0;31mother not-listening   CRASHED  package.wrong-path-sshd-from-bash.cmd.no-port-mapped.centos-6[0m
[0;31mother not-listening   CRASHED  package.wrong-path-sshd-from-bash.cmd.other-port-mapped.centos-6[0m
[1;32mSSHD  listening       RUNNING  compiled7.1-default.sshd.entrypoint.port-mapped.centos-6[0m
other not-listening   RUNNING  compiled7.1-default.sshd.entrypoint.no-port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-default.sshd.entrypoint.other-port-mapped.centos-6
[1;32mSSHD  listening       RUNNING  compiled7.1-default.sshd.cmd.port-mapped.centos-6[0m
other not-listening   RUNNING  compiled7.1-default.sshd.cmd.no-port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-default.sshd.cmd.other-port-mapped.centos-6
[1;32mSSHD  listening       RUNNING  compiled7.1-default.sshd-from-supervisord.entrypoint.port-mapped.centos-6[0m
other not-listening   RUNNING  compiled7.1-default.sshd-from-supervisord.entrypoint.no-port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-default.sshd-from-supervisord.entrypoint.other-port-mapped.centos-6
[1;32mSSHD  listening       RUNNING  compiled7.1-default.sshd-from-supervisord.cmd.port-mapped.centos-6[0m
other not-listening   RUNNING  compiled7.1-default.sshd-from-supervisord.cmd.no-port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-default.sshd-from-supervisord.cmd.other-port-mapped.centos-6
[1;32mSSHD  listening       RUNNING  compiled7.1-default.sshd-from-bash.entrypoint.port-mapped.centos-6[0m
other not-listening   RUNNING  compiled7.1-default.sshd-from-bash.entrypoint.no-port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-default.sshd-from-bash.entrypoint.other-port-mapped.centos-6
[1;32mSSHD  listening       RUNNING  compiled7.1-default.sshd-from-bash.cmd.port-mapped.centos-6[0m
other not-listening   RUNNING  compiled7.1-default.sshd-from-bash.cmd.no-port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-default.sshd-from-bash.cmd.other-port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-default.sleep.entrypoint.port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-default.sleep.entrypoint.no-port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-default.sleep.entrypoint.other-port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-default.sleep.cmd.port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-default.sleep.cmd.no-port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-default.sleep.cmd.other-port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-default.sleep-from-supervisord.entrypoint.port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-default.sleep-from-supervisord.entrypoint.no-port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-default.sleep-from-supervisord.entrypoint.other-port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-default.sleep-from-supervisord.cmd.port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-default.sleep-from-supervisord.cmd.no-port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-default.sleep-from-supervisord.cmd.other-port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-default.sleep-from-bash.entrypoint.port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-default.sleep-from-bash.entrypoint.no-port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-default.sleep-from-bash.entrypoint.other-port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-default.sleep-from-bash.cmd.port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-default.sleep-from-bash.cmd.no-port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-default.sleep-from-bash.cmd.other-port-mapped.centos-6
other listening       RUNNING  compiled7.1-default.nc-server.entrypoint.port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-default.nc-server.entrypoint.no-port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-default.nc-server.entrypoint.other-port-mapped.centos-6
other listening       RUNNING  compiled7.1-default.nc-server.cmd.port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-default.nc-server.cmd.no-port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-default.nc-server.cmd.other-port-mapped.centos-6
other listening       RUNNING  compiled7.1-default.nc-server-from-supervisord.entrypoint.port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-default.nc-server-from-supervisord.entrypoint.no-port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-default.nc-server-from-supervisord.entrypoint.other-port-mapped.centos-6
other listening       RUNNING  compiled7.1-default.nc-server-from-supervisord.cmd.port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-default.nc-server-from-supervisord.cmd.no-port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-default.nc-server-from-supervisord.cmd.other-port-mapped.centos-6
other listening       RUNNING  compiled7.1-default.nc-server-from-bash.entrypoint.port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-default.nc-server-from-bash.entrypoint.no-port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-default.nc-server-from-bash.entrypoint.other-port-mapped.centos-6
other listening       RUNNING  compiled7.1-default.nc-server-from-bash.cmd.port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-default.nc-server-from-bash.cmd.no-port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-default.nc-server-from-bash.cmd.other-port-mapped.centos-6
[0;31mother not-listening   CRASHED  compiled7.1-default.wrong-path-sshd.entrypoint.port-mapped.centos-6[0m
[0;31mother not-listening   CRASHED  compiled7.1-default.wrong-path-sshd.entrypoint.no-port-mapped.centos-6[0m
[0;31mother not-listening   CRASHED  compiled7.1-default.wrong-path-sshd.entrypoint.other-port-mapped.centos-6[0m
[0;31mother not-listening   CRASHED  compiled7.1-default.wrong-path-sshd.cmd.port-mapped.centos-6[0m
[0;31mother not-listening   CRASHED  compiled7.1-default.wrong-path-sshd.cmd.no-port-mapped.centos-6[0m
[0;31mother not-listening   CRASHED  compiled7.1-default.wrong-path-sshd.cmd.other-port-mapped.centos-6[0m
other not-listening   RUNNING  compiled7.1-default.wrong-path-sshd-from-supervisord.entrypoint.port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-default.wrong-path-sshd-from-supervisord.entrypoint.no-port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-default.wrong-path-sshd-from-supervisord.entrypoint.other-port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-default.wrong-path-sshd-from-supervisord.cmd.port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-default.wrong-path-sshd-from-supervisord.cmd.no-port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-default.wrong-path-sshd-from-supervisord.cmd.other-port-mapped.centos-6
[0;31mother not-listening   CRASHED  compiled7.1-default.wrong-path-sshd-from-bash.entrypoint.port-mapped.centos-6[0m
[0;31mother not-listening   CRASHED  compiled7.1-default.wrong-path-sshd-from-bash.entrypoint.no-port-mapped.centos-6[0m
[0;31mother not-listening   CRASHED  compiled7.1-default.wrong-path-sshd-from-bash.entrypoint.other-port-mapped.centos-6[0m
[0;31mother not-listening   CRASHED  compiled7.1-default.wrong-path-sshd-from-bash.cmd.port-mapped.centos-6[0m
[0;31mother not-listening   CRASHED  compiled7.1-default.wrong-path-sshd-from-bash.cmd.no-port-mapped.centos-6[0m
[0;31mother not-listening   CRASHED  compiled7.1-default.wrong-path-sshd-from-bash.cmd.other-port-mapped.centos-6[0m
[1;32mSSHD  listening       RUNNING  compiled7.1-in-opt.sshd.entrypoint.port-mapped.centos-6[0m
other not-listening   RUNNING  compiled7.1-in-opt.sshd.entrypoint.no-port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-in-opt.sshd.entrypoint.other-port-mapped.centos-6
[1;32mSSHD  listening       RUNNING  compiled7.1-in-opt.sshd.cmd.port-mapped.centos-6[0m
other not-listening   RUNNING  compiled7.1-in-opt.sshd.cmd.no-port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-in-opt.sshd.cmd.other-port-mapped.centos-6
[1;32mSSHD  listening       RUNNING  compiled7.1-in-opt.sshd-from-supervisord.entrypoint.port-mapped.centos-6[0m
other not-listening   RUNNING  compiled7.1-in-opt.sshd-from-supervisord.entrypoint.no-port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-in-opt.sshd-from-supervisord.entrypoint.other-port-mapped.centos-6
[1;32mSSHD  listening       RUNNING  compiled7.1-in-opt.sshd-from-supervisord.cmd.port-mapped.centos-6[0m
other not-listening   RUNNING  compiled7.1-in-opt.sshd-from-supervisord.cmd.no-port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-in-opt.sshd-from-supervisord.cmd.other-port-mapped.centos-6
[1;32mSSHD  listening       RUNNING  compiled7.1-in-opt.sshd-from-bash.entrypoint.port-mapped.centos-6[0m
other not-listening   RUNNING  compiled7.1-in-opt.sshd-from-bash.entrypoint.no-port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-in-opt.sshd-from-bash.entrypoint.other-port-mapped.centos-6
[1;32mSSHD  listening       RUNNING  compiled7.1-in-opt.sshd-from-bash.cmd.port-mapped.centos-6[0m
other not-listening   RUNNING  compiled7.1-in-opt.sshd-from-bash.cmd.no-port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-in-opt.sshd-from-bash.cmd.other-port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-in-opt.sleep.entrypoint.port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-in-opt.sleep.entrypoint.no-port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-in-opt.sleep.entrypoint.other-port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-in-opt.sleep.cmd.port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-in-opt.sleep.cmd.no-port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-in-opt.sleep.cmd.other-port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-in-opt.sleep-from-supervisord.entrypoint.port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-in-opt.sleep-from-supervisord.entrypoint.no-port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-in-opt.sleep-from-supervisord.entrypoint.other-port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-in-opt.sleep-from-supervisord.cmd.port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-in-opt.sleep-from-supervisord.cmd.no-port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-in-opt.sleep-from-supervisord.cmd.other-port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-in-opt.sleep-from-bash.entrypoint.port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-in-opt.sleep-from-bash.entrypoint.no-port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-in-opt.sleep-from-bash.entrypoint.other-port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-in-opt.sleep-from-bash.cmd.port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-in-opt.sleep-from-bash.cmd.no-port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-in-opt.sleep-from-bash.cmd.other-port-mapped.centos-6
other listening       RUNNING  compiled7.1-in-opt.nc-server.entrypoint.port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-in-opt.nc-server.entrypoint.no-port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-in-opt.nc-server.entrypoint.other-port-mapped.centos-6
other listening       RUNNING  compiled7.1-in-opt.nc-server.cmd.port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-in-opt.nc-server.cmd.no-port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-in-opt.nc-server.cmd.other-port-mapped.centos-6
other listening       RUNNING  compiled7.1-in-opt.nc-server-from-supervisord.entrypoint.port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-in-opt.nc-server-from-supervisord.entrypoint.no-port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-in-opt.nc-server-from-supervisord.entrypoint.other-port-mapped.centos-6
other listening       RUNNING  compiled7.1-in-opt.nc-server-from-supervisord.cmd.port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-in-opt.nc-server-from-supervisord.cmd.no-port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-in-opt.nc-server-from-supervisord.cmd.other-port-mapped.centos-6
other listening       RUNNING  compiled7.1-in-opt.nc-server-from-bash.entrypoint.port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-in-opt.nc-server-from-bash.entrypoint.no-port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-in-opt.nc-server-from-bash.entrypoint.other-port-mapped.centos-6
other listening       RUNNING  compiled7.1-in-opt.nc-server-from-bash.cmd.port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-in-opt.nc-server-from-bash.cmd.no-port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-in-opt.nc-server-from-bash.cmd.other-port-mapped.centos-6
[0;31mother not-listening   CRASHED  compiled7.1-in-opt.wrong-path-sshd.entrypoint.port-mapped.centos-6[0m
[0;31mother not-listening   CRASHED  compiled7.1-in-opt.wrong-path-sshd.entrypoint.no-port-mapped.centos-6[0m
[0;31mother not-listening   CRASHED  compiled7.1-in-opt.wrong-path-sshd.entrypoint.other-port-mapped.centos-6[0m
[0;31mother not-listening   CRASHED  compiled7.1-in-opt.wrong-path-sshd.cmd.port-mapped.centos-6[0m
[0;31mother not-listening   CRASHED  compiled7.1-in-opt.wrong-path-sshd.cmd.no-port-mapped.centos-6[0m
[0;31mother not-listening   CRASHED  compiled7.1-in-opt.wrong-path-sshd.cmd.other-port-mapped.centos-6[0m
other not-listening   RUNNING  compiled7.1-in-opt.wrong-path-sshd-from-supervisord.entrypoint.port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-in-opt.wrong-path-sshd-from-supervisord.entrypoint.no-port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-in-opt.wrong-path-sshd-from-supervisord.entrypoint.other-port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-in-opt.wrong-path-sshd-from-supervisord.cmd.port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-in-opt.wrong-path-sshd-from-supervisord.cmd.no-port-mapped.centos-6
other not-listening   RUNNING  compiled7.1-in-opt.wrong-path-sshd-from-supervisord.cmd.other-port-mapped.centos-6
[0;31mother not-listening   CRASHED  compiled7.1-in-opt.wrong-path-sshd-from-bash.entrypoint.port-mapped.centos-6[0m
[0;31mother not-listening   CRASHED  compiled7.1-in-opt.wrong-path-sshd-from-bash.entrypoint.no-port-mapped.centos-6[0m
[0;31mother not-listening   CRASHED  compiled7.1-in-opt.wrong-path-sshd-from-bash.entrypoint.other-port-mapped.centos-6[0m
[0;31mother not-listening   CRASHED  compiled7.1-in-opt.wrong-path-sshd-from-bash.cmd.port-mapped.centos-6[0m
[0;31mother not-listening   CRASHED  compiled7.1-in-opt.wrong-path-sshd-from-bash.cmd.no-port-mapped.centos-6[0m
[0;31mother not-listening   CRASHED  compiled7.1-in-opt.wrong-path-sshd-from-bash.cmd.other-port-mapped.centos-6[0m
[1;32mSSHD  listening       RUNNING  compiled5.0-default.sshd.entrypoint.port-mapped.centos-6[0m
other not-listening   RUNNING  compiled5.0-default.sshd.entrypoint.no-port-mapped.centos-6
other not-listening   RUNNING  compiled5.0-default.sshd.entrypoint.other-port-mapped.centos-6
[1;32mSSHD  listening       RUNNING  compiled5.0-default.sshd.cmd.port-mapped.centos-6[0m
other not-listening   RUNNING  compiled5.0-default.sshd.cmd.no-port-mapped.centos-6
other not-listening   RUNNING  compiled5.0-default.sshd.cmd.other-port-mapped.centos-6
[1;32mSSHD  listening       RUNNING  compiled5.0-default.sshd-from-supervisord.entrypoint.port-mapped.centos-6[0m
other not-listening   RUNNING  compiled5.0-default.sshd-from-supervisord.entrypoint.no-port-mapped.centos-6
other not-listening   RUNNING  compiled5.0-default.sshd-from-supervisord.entrypoint.other-port-mapped.centos-6
[1;32mSSHD  listening       RUNNING  compiled5.0-default.sshd-from-supervisord.cmd.port-mapped.centos-6[0m
other not-listening   RUNNING  compiled5.0-default.sshd-from-supervisord.cmd.no-port-mapped.centos-6
other not-listening   RUNNING  compiled5.0-default.sshd-from-supervisord.cmd.other-port-mapped.centos-6
[1;32mSSHD  listening       RUNNING  compiled5.0-default.sshd-from-bash.entrypoint.port-mapped.centos-6[0m
other not-listening   RUNNING  compiled5.0-default.sshd-from-bash.entrypoint.no-port-mapped.centos-6
other not-listening   RUNNING  compiled5.0-default.sshd-from-bash.entrypoint.other-port-mapped.centos-6
[1;32mSSHD  listening       RUNNING  compiled5.0-default.sshd-from-bash.cmd.port-mapped.centos-6[0m
other not-listening   RUNNING  compiled5.0-default.sshd-from-bash.cmd.no-port-mapped.centos-6
other not-listening   RUNNING  compiled5.0-default.sshd-from-bash.cmd.other-port-mapped.centos-6
other not-listening   RUNNING  compiled5.0-default.sleep.entrypoint.port-mapped.centos-6
other not-listening   RUNNING  compiled5.0-default.sleep.entrypoint.no-port-mapped.centos-6
other not-listening   RUNNING  compiled5.0-default.sleep.entrypoint.other-port-mapped.centos-6
other not-listening   RUNNING  compiled5.0-default.sleep.cmd.port-mapped.centos-6
other not-listening   RUNNING  compiled5.0-default.sleep.cmd.no-port-mapped.centos-6
other not-listening   RUNNING  compiled5.0-default.sleep.cmd.other-port-mapped.centos-6
other not-listening   RUNNING  compiled5.0-default.sleep-from-supervisord.entrypoint.port-mapped.centos-6
other not-listening   RUNNING  compiled5.0-default.sleep-from-supervisord.entrypoint.no-port-mapped.centos-6
other not-listening   RUNNING  compiled5.0-default.sleep-from-supervisord.entrypoint.other-port-mapped.centos-6
other not-listening   RUNNING  compiled5.0-default.sleep-from-supervisord.cmd.port-mapped.centos-6
other not-listening   RUNNING  compiled5.0-default.sleep-from-supervisord.cmd.no-port-mapped.centos-6
other not-listening   RUNNING  compiled5.0-default.sleep-from-supervisord.cmd.other-port-mapped.centos-6
other not-listening   RUNNING  compiled5.0-default.sleep-from-bash.entrypoint.port-mapped.centos-6
other not-listening   RUNNING  compiled5.0-default.sleep-from-bash.entrypoint.no-port-mapped.centos-6
other not-listening   RUNNING  compiled5.0-default.sleep-from-bash.entrypoint.other-port-mapped.centos-6
other not-listening   RUNNING  compiled5.0-default.sleep-from-bash.cmd.port-mapped.centos-6
other not-listening   RUNNING  compiled5.0-default.sleep-from-bash.cmd.no-port-mapped.centos-6
other not-listening   RUNNING  compiled5.0-default.sleep-from-bash.cmd.other-port-mapped.centos-6
other listening       RUNNING  compiled5.0-default.nc-server.entrypoint.port-mapped.centos-6
other not-listening   RUNNING  compiled5.0-default.nc-server.entrypoint.no-port-mapped.centos-6
other not-listening   RUNNING  compiled5.0-default.nc-server.entrypoint.other-port-mapped.centos-6
other listening       RUNNING  compiled5.0-default.nc-server.cmd.port-mapped.centos-6
other not-listening   RUNNING  compiled5.0-default.nc-server.cmd.no-port-mapped.centos-6
other not-listening   RUNNING  compiled5.0-default.nc-server.cmd.other-port-mapped.centos-6
other listening       RUNNING  compiled5.0-default.nc-server-from-supervisord.entrypoint.port-mapped.centos-6
other not-listening   RUNNING  compiled5.0-default.nc-server-from-supervisord.entrypoint.no-port-mapped.centos-6
other not-listening   RUNNING  compiled5.0-default.nc-server-from-supervisord.entrypoint.other-port-mapped.centos-6
other listening       RUNNING  compiled5.0-default.nc-server-from-supervisord.cmd.port-mapped.centos-6
other not-listening   RUNNING  compiled5.0-default.nc-server-from-supervisord.cmd.no-port-mapped.centos-6
other not-listening   RUNNING  compiled5.0-default.nc-server-from-supervisord.cmd.other-port-mapped.centos-6
other listening       RUNNING  compiled5.0-default.nc-server-from-bash.entrypoint.port-mapped.centos-6
other not-listening   RUNNING  compiled5.0-default.nc-server-from-bash.entrypoint.no-port-mapped.centos-6
other not-listening   RUNNING  compiled5.0-default.nc-server-from-bash.entrypoint.other-port-mapped.centos-6
other listening       RUNNING  compiled5.0-default.nc-server-from-bash.cmd.port-mapped.centos-6
other not-listening   RUNNING  compiled5.0-default.nc-server-from-bash.cmd.no-port-mapped.centos-6
other not-listening   RUNNING  compiled5.0-default.nc-server-from-bash.cmd.other-port-mapped.centos-6
[0;31mother not-listening   CRASHED  compiled5.0-default.wrong-path-sshd.entrypoint.port-mapped.centos-6[0m
[0;31mother not-listening   CRASHED  compiled5.0-default.wrong-path-sshd.entrypoint.no-port-mapped.centos-6[0m
[0;31mother not-listening   CRASHED  compiled5.0-default.wrong-path-sshd.entrypoint.other-port-mapped.centos-6[0m
[0;31mother not-listening   CRASHED  compiled5.0-default.wrong-path-sshd.cmd.port-mapped.centos-6[0m
[0;31mother not-listening   CRASHED  compiled5.0-default.wrong-path-sshd.cmd.no-port-mapped.centos-6[0m
[0;31mother not-listening   CRASHED  compiled5.0-default.wrong-path-sshd.cmd.other-port-mapped.centos-6[0m
other not-listening   RUNNING  compiled5.0-default.wrong-path-sshd-from-supervisord.entrypoint.port-mapped.centos-6
other not-listening   RUNNING  compiled5.0-default.wrong-path-sshd-from-supervisord.entrypoint.no-port-mapped.centos-6
other not-listening   RUNNING  compiled5.0-default.wrong-path-sshd-from-supervisord.entrypoint.other-port-mapped.centos-6
other not-listening   RUNNING  compiled5.0-default.wrong-path-sshd-from-supervisord.cmd.port-mapped.centos-6
other not-listening   RUNNING  compiled5.0-default.wrong-path-sshd-from-supervisord.cmd.no-port-mapped.centos-6
other not-listening   RUNNING  compiled5.0-default.wrong-path-sshd-from-supervisord.cmd.other-port-mapped.centos-6
[0;31mother not-listening   CRASHED  compiled5.0-default.wrong-path-sshd-from-bash.entrypoint.port-mapped.centos-6[0m
[0;31mother not-listening   CRASHED  compiled5.0-default.wrong-path-sshd-from-bash.entrypoint.no-port-mapped.centos-6[0m
[0;31mother not-listening   CRASHED  compiled5.0-default.wrong-path-sshd-from-bash.entrypoint.other-port-mapped.centos-6[0m
[0;31mother not-listening   CRASHED  compiled5.0-default.wrong-path-sshd-from-bash.cmd.port-mapped.centos-6[0m
[0;31mother not-listening   CRASHED  compiled5.0-default.wrong-path-sshd-from-bash.cmd.no-port-mapped.centos-6[0m
[0;31mother not-listening   CRASHED  compiled5.0-default.wrong-path-sshd-from-bash.cmd.other-port-mapped.centos-6[0m
[1;32mSSHD  listening       RUNNING  compiled5.0-in-opt.sshd.entrypoint.port-mapped.centos-6[0m
other not-listening   RUNNING  compiled5.0-in-opt.sshd.entrypoint.no-port-mapped.centos-6
other not-listening   RUNNING  compiled5.0-in-opt.sshd.entrypoint.other-port-mapped.centos-6
[1;32mSSHD  listening       RUNNING  compiled5.0-in-opt.sshd.cmd.port-mapped.centos-6[0m
other not-listening   RUNNING  compiled5.0-in-opt.sshd.cmd.no-port-mapped.centos-6
other not-listening   RUNNING  compiled5.0-in-opt.sshd.cmd.other-port-mapped.centos-6
[1;32mSSHD  listening       RUNNING  compiled5.0-in-opt.sshd-from-supervisord.entrypoint.port-mapped.centos-6[0m
other not-listening   RUNNING  compiled5.0-in-opt.sshd-from-supervisord.entrypoint.no-port-mapped.centos-6
other not-listening   RUNNING  compiled5.0-in-opt.sshd-from-supervisord.entrypoint.other-port-mapped.centos-6
[1;32mSSHD  listening       RUNNING  compiled5.0-in-opt.sshd-from-supervisord.cmd.port-mapped.centos-6[0m
other not-listening   RUNNING  compiled5.0-in-opt.sshd-from-supervisord.cmd.no-port-mapped.centos-6
other not-listening   RUNNING  compiled5.0-in-opt.sshd-from-supervisord.cmd.other-port-mapped.centos-6
[1;32mSSHD  listening       RUNNING  compiled5.0-in-opt.sshd-from-bash.entrypoint.port-mapped.centos-6[0m
other not-listening   RUNNING  compiled5.0-in-opt.sshd-from-bash.entrypoint.no-port-mapped.centos-6
other not-listening   RUNNING  compiled5.0-in-opt.sshd-from-bash.entrypoint.other-port-mapped.centos-6
[1;32mSSHD  listening       RUNNING  compiled5.0-in-opt.sshd-from-bash.cmd.port-mapped.centos-6[0m
other not-listening   RUNNING  compiled5.0-in-opt.sshd-from-bash.cmd.no-port-mapped.centos-6
other not-listening   RUNNING  compiled5.0-in-opt.sshd-from-bash.cmd.other-port-mapped.centos-6
